POST http://localhost:4000/patient
Content-Type: application/json
{
    "name":"Srujan",
    "email":"codewithsrujan@email.com",
 "phoneNumber":"8310081087",
 "priority":"1",
 "dateOfBirth":"2006-07-21",
 "registerDate":"2024-02-02"
}